
services:
  # خدمة الواجهة الأمامية
  - type: web
    name: textify-upload
    env: node
    buildCommand: npm install && npx vite build
    startCommand: PORT=10000 node src/server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
      - key: AUTOMATION_SERVER_URL
        value: https://textify-upload.onrender.com
      - key: VITE_AUTOMATION_SERVER_URL
        value: https://textify-upload.onrender.com
    healthCheckPath: /api/status
    healthCheckTimeout: 150
    autoDeploy: true

    # إعدادات الموارد
    plan: free

    # ضبط منطقة النشر
    region: ohio

# متغيرات عالمية مشتركة بين جميع الخدمات
envVarGroups:
  - name: common-settings
    envVars:
      - key: NODE_VERSION
        value: 18
