
services:
  # خدمة الواجهة الأمامية
  - type: web
    name: textify-upload
    env: node
    buildCommand: npm install && VITE_AUTOMATION_SERVER_URL=${RENDER_EXTERNAL_URL} npm run build
    startCommand: node src/server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: textify-upload
          envVarKey: PORT
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
      - key: AUTOMATION_SERVER_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: VITE_AUTOMATION_SERVER_URL
        value: ${RENDER_EXTERNAL_URL}
      - key: RENDER_EXTERNAL_URL
        sync: false
    healthCheckPath: /api/status
    healthCheckTimeout: 150
    autoDeploy: true

    # إعدادات الموارد
    plan: free

    # ضبط منطقة النشر
    region: ohio

# متغيرات عالمية مشتركة بين جميع الخدمات
envVarGroups:
  - name: common-settings
    envVars:
      - key: NODE_VERSION
        value: 18
