// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fepwckdjnmizplgqebgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlcHdja2Rqbm1penBsZ3FlYmdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTQ1MDgsImV4cCI6MjA1ODU3MDUwOH0.t-qUEPPSwOUJezoFaX0rasqDzuEd5yM1w1uVZWnSX7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);